### ISSUE TITLE
optcarrot

### ISSUE THREAD

**Issue by nateberkopec** [ruby-bench/ruby-bench-suite#73]
Matz said during Q&A at Rubyconf 2016 that the core team currently think that the Ruby 3x3 goal will be measured against the optcarrot benchmark - i.e. Ruby 3.0 should perform the optcarrot bench 3 times faster than Ruby 2.0. So, ruby-bench should probably run optcarrot.

**Comment by tgxworld** [comment]
Hi @nateberkopec, this is on my to-do list. I'm hoping to get the benchmarks up soon :)

**Comment by nateberkopec** [comment]
👍 Thanks for all of your hard work on this project!

**Comment by tgxworld** [comment]
I'm only running benchmarks for the default mode and I'll need to figure out why some of the Ruby versions do not work with the benchmark. Otherwise, preliminary results for different ruby versions are up @ https://rubybench.org/ruby/ruby/releases?result_type=Optcarrot%20Lan_Master.nes. I'll be backfilling 2000 commits as well.

**Comment by tgxworld** [comment]
Closing this for now :)
